-- MySQL Script generated by MySQL Workbench
-- vie 24 ene 2020 15:42:50 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pesb2DB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pesb2DB` ;

-- -----------------------------------------------------
-- Schema pesb2DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pesb2DB` DEFAULT CHARACTER SET utf8 ;
USE `pesb2DB` ;

-- -----------------------------------------------------
-- Table `pesb2DB`.`integrante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pesb2DB`.`integrante` ;

CREATE TABLE IF NOT EXISTS `pesb2DB`.`integrante` (
  `idintegrante` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `posicion` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(450) NOT NULL,
  `linkedin` VARCHAR(450) NOT NULL,
  `scholarProfile` VARCHAR(450) NOT NULL,
  `researchGateProfile` VARCHAR(450) NOT NULL,
  `fotoPrincipal` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(4500) NOT NULL,
  PRIMARY KEY (`idintegrante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pesb2DB`.`publicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pesb2DB`.`publicacion` ;

CREATE TABLE IF NOT EXISTS `pesb2DB`.`publicacion` (
  `idpublicacion` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `estadoPublicacion` VARCHAR(45) NOT NULL,
  `linkAcceso` VARCHAR(45) NULL,
  `autorPrincipal` INT NOT NULL,
  PRIMARY KEY (`idpublicacion`),
  INDEX `fk_publicacion_integrante_idx` (`autorPrincipal` ASC),
  CONSTRAINT `fk_publicacion_integrante`
    FOREIGN KEY (`autorPrincipal`)
    REFERENCES `pesb2DB`.`integrante` (`idintegrante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pesb2DB`.`proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pesb2DB`.`proyecto` ;

CREATE TABLE IF NOT EXISTS `pesb2DB`.`proyecto` (
  `idproyecto` INT NOT NULL,
  `nombreProyecto` VARCHAR(450) NOT NULL,
  `descripcionProyecto` VARCHAR(4500) NOT NULL,
  `financiamiento` VARCHAR(450) NOT NULL,
  `encargadoProyecto` INT NOT NULL,
  PRIMARY KEY (`idproyecto`),
  INDEX `fk_proyecto_integrante1_idx` (`encargadoProyecto` ASC),
  CONSTRAINT `fk_proyecto_integrante1`
    FOREIGN KEY (`encargadoProyecto`)
    REFERENCES `pesb2DB`.`integrante` (`idintegrante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
